version: "3.8"

services:
  frontend:
    build: ./daos-frontend
    image: frontimage
    container_name: frontcontainer
    restart: unless-stopped
    environment:
      NODE_ENV: "production"
    ports:
      - "3000:3000"
    command: bash -c " npm run dev"
