version: "3.7"

services:
  frontend:
    build: ./daos-frontend
    image: frontimage
    container_name: frontcontainer
    restart: always
    # environment:
    #   NODE_ENV: "production"
    depends_on:
      - backend
    ports:
      - "3000:3000"
    command: bash -c " npm run dev"
    # volumes:
    #   - ./daos-frontend:/app
    volumes:
      - frontenddata:/data/frontend
    networks:
      - frontbacknetwork
  backend:
    build: ./daos-backend
    image: backimage
    container_name: backcontainer
    restart: always
    ports:
      - "5000:3007"
    environment:
      connection_string: mongodb://mongodb:27017/users?directConnection=true
      port: 3007
      jwt_secret: dragons
    depends_on:
      - mongodb
    # volumes:
    #   - ./daos-backend:/app
    volumes:
      - backenddata:/data/backend
    networks:
      - backdbnetwork
      - frontbacknetwork
  mongodb:
    image: mongo
    container_name: mongocontainer
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - backdbnetwork

volumes:
  dbdata:
  frontenddata:
    driver: local
    driver_opts:
      type: none
      device: ${ABSOLUTE_PATH}/daos-frontend
      o: bind
  backenddata:
    driver: local
    driver_opts:
      type: none
      device: ${ABSOLUTE_PATH}/daos-backend
      o: bind
networks:
  backdbnetwork:
    driver: bridge
  frontbacknetwork:
    driver: bridge
